#!/bin/bash

#cleanup before making a mess
rm dirobash-entries

#scrape dirobash posts
for i in `seq 1 29`;
do
  curl http://dirobash.tolarian.com/$i | tail -n +30 | awk '!/<blockquote>/ && !/<div>/ && !/<\/div>/ && !/<\/blockquote>/ && !/<div id="pagination">/ && !/<p>/ && !/<\/p>/ && !/<div class="quote">/ && !/<a href=".*">/ && !/<div id="quotes">/ && !/<\/body>/ && !/<\/html>/' >> raw-dirobash-entries
done

#replace special characters
sed -e 's/&deg;/°/g' -e 's/&macr;/¯/g' -e 's/&nbsp;/ /g' -e 's/&copy;/©/g' -e 's/&shy;//g' -e 's/&Acirc;/Â/g' -e 's/&iuml;/ï/g' -e 's/&icirc;/î/g' -e 's/&Egrave;/È/g' -e 's/&oacute;/ó/g' -e 's/&ouml;/ö/g' -e 's/&Atilde;/Ã/g' -e 's/&Agrave;/À/g' -e 's/&amp;/\&/g' -e 's/&acirc;/â/g' -e 's/&ocirc;/ô/g' -e 's/&Eacute;/É/g' -e 's/&ucirc;/û/g' -e 's/&laquo;/«/g' -e 's/&raquo;/»/g' -e 's/&uuml;/ü/g' -e 's/&Iuml;/Ï/g' -e 's/&euml;/ë/g' -e 's/&Ccedil;/Ç/g' -e 's/&agrave;/à/g' -e 's/&ecirc;/ê/g' -e 's/&egrave;/è/g' -e 's/&quot;/"/g' -e 's/<br \/>//g' -e 's///g' -e 's/&eacute;/é/g' -e 's/&lt;/</g' -e 's/&gt;/>/g' -e 's/&ccedil;/ç/g' -e 's/&ugrave;/ù/g' raw-dirobash-entries > dirobash-entries
